/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.infosystem.dynamicDatabase.builder;

import com.infosystem.dynamicDatabase.model.ColumnDefinition;
import com.infosystem.dynamicDatabase.model.DataType;
import com.infosystem.dynamicDatabase.model.DictionaryValue;
import java.util.ArrayList;
import java.util.List;

public class ColumnDefinitionBuilder extends ColumnDefinitionBuilderBase<ColumnDefinitionBuilder> {
	public static ColumnDefinitionBuilder columnDefinition() {
		return new ColumnDefinitionBuilder();
	}

	public ColumnDefinitionBuilder() {
		super(new ColumnDefinition());
	}

	public ColumnDefinition build() {
		return getInstance();
	}
}

class ColumnDefinitionBuilderBase<GeneratorT extends ColumnDefinitionBuilderBase<GeneratorT>> {
	private ColumnDefinition instance;

	protected ColumnDefinitionBuilderBase(ColumnDefinition aInstance) {
		instance = aInstance;
	}

	protected ColumnDefinition getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withId(String aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withOrder(int aValue) {
		instance.setOrder(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withRequired(boolean aValue) {
		instance.setRequired(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withHtmlLabel(String aValue) {
		instance.setHtmlLabel(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPlainLabel(String aValue) {
		instance.setPlainLabel(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDataType(DataType aValue) {
		instance.setDataType(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTable_id(int aValue) {
		instance.setTable_id(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withGroupId(String aValue) {
		instance.setGroupId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDictionaryValues(List<DictionaryValue> aValue) {
		instance.setDictionaryValues(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAddedDictionaryValue(DictionaryValue aValue) {
		if (instance.getDictionaryValues() == null) {
			instance.setDictionaryValues(new ArrayList<DictionaryValue>());
		}

		((ArrayList<DictionaryValue>) instance.getDictionaryValues()).add(aValue);

		return (GeneratorT) this;
	}

	public AddedDictionaryValueDictionaryValueBuilder withAddedDictionaryValue() {
		DictionaryValue obj = new DictionaryValue();

		withAddedDictionaryValue(obj);

		return new AddedDictionaryValueDictionaryValueBuilder(obj);
	}

	public class AddedDictionaryValueDictionaryValueBuilder extends
			DictionaryValueBuilderBase<AddedDictionaryValueDictionaryValueBuilder> {
		public AddedDictionaryValueDictionaryValueBuilder(DictionaryValue aInstance) {
			super(aInstance);
		}

		@SuppressWarnings("unchecked")
		public GeneratorT endDictionaryValue() {
			return (GeneratorT) ColumnDefinitionBuilderBase.this;
		}
	}

	public static class DictionaryValueBuilderBase<GeneratorT extends DictionaryValueBuilderBase<GeneratorT>> {
		private DictionaryValue instance;

		protected DictionaryValueBuilderBase(DictionaryValue aInstance) {
			instance = aInstance;
		}

		protected DictionaryValue getInstance() {
			return instance;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withId(String aValue) {
			instance.setId(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withHtmlLabel(String aValue) {
			instance.setHtmlLabel(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withPlainLabel(String aValue) {
			instance.setPlainLabel(aValue);

			return (GeneratorT) this;
		}
	}
}
